name: flutter_pcsc_windows
description: Windows implementation of the flutter_pcsc plugin for using PCSC smartcard readers.
version: 0.0.3
repository: https://github.com/fabienrousseau/flutter_pcsc

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.0.0
  flutter_pcsc_platform_interface: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  ffigen: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    implements: flutter_pcsc
    platforms:
      windows:
        pluginClass: none
        dartPluginClass: PcscWindows

ffigen:
  name: NativeLibraryWinscard
  description: Bindings to winscard.dll
  output: 'generated_bindings.dart'
  llvm-path: 
    - 'E:/Program/Android/AndSDK/ndk/26.1.10909125/toolchains/llvm/prebuilt/windows-x86_64'
  headers:
    entry-points:
      - 'headers/winscard.h'
    include-directives:
      - '**winscard.h'
